### ISSUE TITLE
Can't drop image to the iconizer

### ISSUE THREAD

**Issue by saltwat5r** [raphaelhanneken/iconizer#10]
Hi! I have a problem with dropping image to the app. It can't be dropped at the area for image.
I'm running it on the macOS Sierra 10.12.1

**Comment by raphaelhanneken** [comment]
Hi there! 
I can't reproduce the error. Can you tell me, which Iconizer version you're using and the image format you're trying to convert?

**Comment by saltwat5r** [comment]
I'm using Version 2.2.3 (212). I'm trying to use png and jpg images.

**Comment by raphaelhanneken** [comment]
I'm sorry, but I have to go with the least satisfying answer here: That's weird...
I can drag, drop and export jpg, png, icon and pdf images, all working just fine. Could you please check your system logs for any errors, while dropping an image onto Iconizer? 
Also, can you share the image you're trying to export with me, actually I don't know why the image should be the problem but I'm running out of ideas.

**Comment by saltwat5r** [comment]
Sample image: ![arrow](https://cloud.githubusercontent.com/assets/4674099/21390726/a048adc2-c788-11e6-9a29-bd201e3e7ec5.png)

**Comment by saltwat5r** [comment]
And I've just seen that in File menu I can't use "Open" option  

<img width="178" alt="Menu" src="https://cloud.githubusercontent.com/assets/4674099/21426865/94415cbc-c851-11e6-9011-abaa5432c88e.png">

**Comment by raphaelhanneken** [comment]
Ok, I've released a new version. Hopefully this fixes the problem.

**Comment by saltwat5r** [comment]
Great! Thanks! Now it works 😄

**Comment by raphaelhanneken** [comment]
Awesome!  🎉
