### ISSUE TITLE
The generated images have the same dimensions

### ISSUE THREAD

**Issue by MaG21** [raphaelhanneken/iconizer#13]
All the resulting images have the same dimensions, although the resulting `Contents.json` seems correct.

<img width="1339" alt="screen shot 2017-11-25 at 12 16 34 pm" src="https://user-images.githubusercontent.com/1760771/33232328-cc09691c-d1da-11e7-8498-bebf3aae0a0d.png">

**Comment by raphaelhanneken** [comment]
Classic regression, some proper tests would have prevented this issue. I've just released a new Iconizer version, which should hopefully fix this.
Thank's @MaG21 for reporting. 👍
