### ISSUE TITLE
Deprecated Launch Screen image dimensions

### ISSUE THREAD

**Issue by MaG21** [raphaelhanneken/iconizer#14]
The resulting images don't have the dimensions Apple advises on their [Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/launch-screen/)

![screen shot 2017-11-27 at 9 42 51 am](https://user-images.githubusercontent.com/1760771/33269745-214d8fd8-d358-11e7-83ff-2f0e40af8515.png)

**Comment by raphaelhanneken** [comment]
Should be fixed with version 2.2.7
