### ISSUE TITLE
[Launch Image view] Allow the use of one orientation only

### ISSUE THREAD

**Issue by MaG21** [raphaelhanneken/iconizer#15]
What if an app's orientation does not support Landscape?
The iconizer shall allow users to generate images for the orientation they want. Landscape only, Portrait only or for both.

<img width="552" alt="screen shot 2017-11-27 at 9 55 00 am" src="https://user-images.githubusercontent.com/1760771/33270075-326f05ac-d359-11e7-9615-7d52a39be5fe.png">

**Comment by raphaelhanneken** [comment]
I didn't know this was a use case. Thanks for reporting this. 👍

**Comment by raphaelhanneken** [comment]
Released with [version 2.4.0](https://github.com/raphaelhanneken/iconizer/releases/download/2.4.0/Iconizer.dmg).
