### ISSUE TITLE
AppIcon - AppStore version is missing

### ISSUE THREAD

**Issue by pionl** [raphaelhanneken/iconizer#16]
Appstore versions is not included any more on latest version :)

**Comment by vickydhas** [comment]
Sparkle.framework was not found when i took source code and tried to add this icon 1024x1024 that is now required by IOS 11

**Comment by raphaelhanneken** [comment]
Should be fixed with version 2.3. Thanks for reporting! 👍

@vickydhas to compile Iconizer you first have to run `carthage update` inside the Iconizer directory; Assuming you've installed [Carthage](https://github.com/Carthage/Carthage)
