### ISSUE TITLE
Choose between AspectFit and AspectFill

### ISSUE THREAD

**Issue by PabloHenri91** [raphaelhanneken/iconizer#18]
The app always uses AspectFill witch sometimes crops the image. 
That would be great to choose  between aspectFit and aspectFill.

https://stackoverflow.com/questions/4895272/difference-between-uiviewcontentmodescaleaspectfit-and-uiviewcontentmodescaletof

**Comment by raphaelhanneken** [comment]
Hey @PabloHenri91, thanks for this great idea. The feature is implemented in v2.5.0 👍
