### ISSUE TITLE
Launch image missing sizes

### ISSUE THREAD

**Issue by saedelman** [raphaelhanneken/iconizer#19]
I can't get any of the launch image sizes generated to be compatible with the latest version of XCode 9.3.1. I have not been able to match up a single launch image. I have an exclamation badge on every launch image that indicates the size is not as desired. Can this be fixed?

**Comment by raphaelhanneken** [comment]
Hey @saedelman, thanks for reporting this issue. I've just released version 2.5.1, which should hopefully fix the issue. 👍
