### ISSUE TITLE
生成的icon alpha通道默认打开了

### ISSUE THREAD

**Issue by fenglee594** [raphaelhanneken/iconizer#23]

**Comment by fenglee594** [comment]
the alpha channel is always opened when use this tool generate app icons

**Comment by formatCvt** [comment]
same issue

**Comment by raphaelhanneken** [comment]
Can you provide an example? What input image are you using? How does it affect the outcome?

**Comment by formatCvt** [comment]
source with no alpha
![source-1024 1024-icon-with-no-alpha](https://user-images.githubusercontent.com/9342933/52699620-3d79e580-2f87-11e9-9a32-25ae47b0ab21.png)
result with alpha
![ios-marketing-result-with-alpha](https://user-images.githubusercontent.com/9342933/52699645-4cf92e80-2f87-11e9-9adb-88d80d1c9f76.png)

**Comment by raphaelhanneken** [comment]
Thanks! Will look into this asap 👍

**Comment by raphaelhanneken** [comment]
Should be resolved with v2.6.1

**Comment by ravindu1024** [comment]
@raphaelhanneken @fenglee594  Are you guys sure this alpha channel issue applies to ios App icons as well? I just submitted an update 2 days ago with an App icon I generated using an older version - which includes alpha. The only thing iTunes rejects is alpha in the store icon (Marketing image). They allow alpha in app icons. Version 2.6.1 removes alpha from all icon sizes which is not required.
