### ISSUE TITLE
Maybe wrong calculation

### ISSUE THREAD

**Issue by saxija** [raphaelhanneken/iconizer#24]
Hello, I have been using this app for a while and recently noticed something strange. If I put 72x72 image as @3x it generates 36x36 for @2x and 18x18 for @1x. I am using 2.6.1, and same was for version before. Maybe I am wrong but should it be 72 >> 48 >> 24? 

![image 1x](https://user-images.githubusercontent.com/34780991/53693965-d5f5cf80-3da7-11e9-92aa-41f8ff0a8a71.png)
![image 2x](https://user-images.githubusercontent.com/34780991/53693966-d5f5cf80-3da7-11e9-9eda-08c238ec25f9.png)
![image 3x](https://user-images.githubusercontent.com/34780991/53693967-d68e6600-3da7-11e9-8696-e65a4fe4bf77.png)

By apple documentation it says:

72px × 72px (24pt × 24pt @3x) 
48px × 48px (24pt × 24pt @2x)

size @1x should be multiplied with 2 and 3. Thanks!

**Comment by raphaelhanneken** [comment]
Hi @saxija you‘re right. Thanks a lot für reporting this. I will look into it asap. 👍

**Comment by saxija** [comment]
That was fast :D

**Comment by raphaelhanneken** [comment]
This should be fixed with version 2.6.2 (286). Excellent bug report btw, it contained all the information I needed - right from the get go. Thanks again!
