### ISSUE TITLE
Allow alpha channels in App Icons

### ISSUE THREAD

**Issue by ravindu1024** [raphaelhanneken/iconizer#25]
The app store only rejects alpha channels in the "App Store" image of the combined AppIcon asset. They allow alpha in the actual app icons. Update 2.6.1 removes alpha from all images in the combined AppIcon asset - but should only remove it from the "App Store" image.

**Comment by raphaelhanneken** [comment]
Hi @ravindu1024, thanks for clarifying this! Just to be sure: Except the marketing image for the App Store every image is allowed to contain an alpha channel?

**Comment by ravindu1024** [comment]
No problem. I have been using older versions of Iconizer and all I do is change the Store image from the combined asset to a jpg and iTunes accepts it. The last update I did to my app was last week. So yeah, can confirm that they allow alpha channels in all other images in the icon asset.
Imagine my surprise when Iconizer suddenly added a white background to all my icons lol. 

ps: This is a really useful app - kudos for building it :+1:

**Comment by raphaelhanneken** [comment]
This should be fixed with version 2.6.3. I'm really happy you find Iconizer useful. Thanks again! 👍

**Comment by marchv** [comment]
Hi and yes great tool! :)

But shouldn't all icons have no transparency?

'Flattened with no transparency' according to https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/

Cheers!

**Comment by sraka1** [comment]
@raphaelhanneken based on Apples guidelines, all appicons should be flattened (without alpha). Also, [this](https://github.com/raphaelhanneken/iconizer/blob/00adbf2a3d9c6ceeacb5af3a46eb6e5b2dabd1ad/Iconizer/Models/AppIcon.swift#L117) bit does not seem to work - I'm getting an alpha channel in the marketing image (and thus rejected when uploading to App Store Connect).
