### ISSUE TITLE
Launch images missing sizes [2]

### ISSUE THREAD

**Issue by Insality** [raphaelhanneken/iconizer#27]
Hello! I am using your software to generate launch images, and I don't see next sizes:

1334x750 (but 750x1334 exist)
1668x2224
2224x1668
2048x2732
2732x2048

**Comment by raphaelhanneken** [comment]
Hi! Thanks for reporting! I'll look into it asap.

**Comment by raphaelhanneken** [comment]
Hey @Insality! Can you tell me where the image sizes are missing? When I generate a launch image and add it to Xcode (version 10.2.1 (10E1001)), it tells me everything is fine. No missing images there.

**Comment by Insality** [comment]
I am using Defold (game engine) and it is required exactly this image sizes

By anyway, strange thing: 750x1334 exist, but landscape version not generated

As I know, this huge image sizes for new ipads

**Comment by Insality** [comment]
@raphaelhanneken there is source with list of sizes
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/

**Comment by Kirow** [comment]
Hi @Insality ,
All image sets were made to match xcode's needs exactly, to let user just drag and drop result folder.
There is no need for `1334x750` if you setup LaunchScreen from `.xcassets`.

For your case I can suggest you to modify package resource `Iconizer.app/Contents/Resources/LaunchImage_iPhone_Landscape.json`
add additional object to json:
```json
      {
        "extent" : "full-screen",
        "idiom" : "iphone",
        "subtype" : "667h",
        "minimum-system-version" : "8.0",
        "orientation" : "landscape",
        "scale" : "2x",
        "size": "1334x750"
      }
```
However if you will use generated folder in  in xcode, you will see `The launch image set has an unassigned child.` warning.

**Comment by raphaelhanneken** [comment]
Thanks @Kirow for clarifying this. 👍
