### ISSUE TITLE
60x60 x2 appicons not generated

### ISSUE THREAD

**Issue by rlegault33** [raphaelhanneken/iconizer#29]
When only ipad and iPhone is selected it did not generate the 60x60 app image. When I left the defaults selected that 60x60 image was created.

**Comment by Kirow** [comment]
Hi @rlegault33, 
checked the app, worked as expected. I guess it is naming issue in your case. 60x60@2x is `icon-120.png`. You should just drag `.appiconset` folder to your `.xcassets` and you will see all icons in place.
