### ISSUE TITLE
Homepage Down & Instructions for Launch Image

### ISSUE THREAD

**Issue by tonydehnke** [raphaelhanneken/iconizer#36]
Hi, the link to the Homepage from the readme is down.

As well, (and I'm guessing they were on the homepage), so instructions on what images sizes to use in the Launch Images area would be good.

**Comment by raphaelhanneken** [comment]
Hi @tonydehnke,
I've added a custom domain for my GitHub Pages, the new url is: https://raphaelhanneken.com/iconizer
I haven't thought about the effects it would have on my other repos. Thanks a lot for letting me know.

**Comment by tonydehnke** [comment]
Cool, thanks.. I like how you have the recommended sizes for Launch images, might be good to add to the Image Sets area too?

**Comment by raphaelhanneken** [comment]
Image Sets can be anything, so there is no recommended size or aspect ratio. Iconizer will just scale the image you dropped down to its @2x and @1x sizes.
