### ISSUE TITLE
Images generated are double in size

### ISSUE THREAD

**Issue by masarapmabuhay** [raphaelhanneken/iconizer#6]
Hello! My teammate uses your Iconizer app a lot, and he recommended it to me. Unfortunately, when I generate app icons using Iconizer myself, the dimensions of the images are double in size. For example, for the ipad-appicon@1x.png, I get 152x152, instead of 76x76.

Also, interestingly, Iconizer does not generate an app icon for ipad-pro-appicon@1x.png.

I tested both 2.2. and 2.2.1 for this. I set iPhone and iPad as my Platforms and checked "Export as Combined Asset". I'm using El Capitan 10.11.5. 

I've also removed the previous app icon set that Iconizer generated, and then generated the icons again, to see if the issue is related to the overwriting process done by Iconizer. But to no avail.

I hope you can help us figure out a workaround to this. We suspect that it might be a bug in the Iconizer app, but it is also possible that I missed an otherwise obvious step.

Thank you so much.

**Comment by chrisamanse** [comment]
@raphaelhanneken this may be an issue with resizing images from a MacBook with a Retina screen. Here's the related [Stackoverflow discussion](http://stackoverflow.com/questions/17507170/how-to-save-png-file-from-nsimage-retina-issues).

**Comment by dcilia** [comment]
Just came upon the need to use this app;  here is the fix for the retina issue.

https://github.com/raphaelhanneken/iconizer/pull/9

@raphaelhanneken

**Comment by raphaelhanneken** [comment]
Thanks guys. I've merged the pr and published a new release, hope this works now.
